### ISSUE TITLE
Add protection against net negative trades

### ISSUE THREAD

**Issue by cribbstechnologies** [R4stl1n/condex#3]
Make sure that there's protection around rebalancing so that trade fees don't negate much of what the engine is trying to accomplish

**Comment by R4stl1n** [comment]
I believe in order to achieve this we will have to weight lower percentages. So essentially higher percentages take a larger hit when adding a new coin than it being equal among all of the selected coins.

Example:

ETH 15% Not Locked
NEO 5% Not Locked
------------------------

When we add XRP at 3% it should take 2% from ETH and 1% from NEO. Same idea for more coins in the index. Smaller ones loss less.

**Comment by r4stl1n** [comment]
Currently the bot does not trade for a loss. So do not believe this is a issue.
